### ISSUE TITLE
Network connection timed-out.

### ISSUE THREAD

**Issue by VadneyK** [PlasmNetwork/Hardhat-tutorial#1]
M1 MacOS BigSur 11.2.3

I'm trying to deploy to dusty via hardhat but am having issues.

![Screen Shot 2021-06-01 at 9 34 56 PM](https://user-images.githubusercontent.com/57117207/120424445-38d8c700-c321-11eb-87aa-b89baa0d6796.png)

error message:

```sh
kentarovadney@Kentaros-MacBook-Air Hardhat-tutorial % npx hardhat run --network dusty scripts/deploy.js
HardhatError: HH109: Network connection timed-out.
Please check your internet connection and networks config
    at HttpProvider._fetchJsonRpcResponse (/Users/kentarovadney/Desktop/Hardhat-tutorial/node_modules/hardhat/src/internal/core/providers/http.ts:175:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at HttpProvider.request (/Users/kentarovadney/Desktop/Hardhat-tutorial/node_modules/hardhat/src/internal/core/providers/http.ts:52:29)
    at GanacheGasMultiplierProvider._isGanache (/Users/kentarovadney/Desktop/Hardhat-tutorial/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:186:30)
    at GanacheGasMultiplierProvider.request (/Users/kentarovadney/Desktop/Hardhat-tutorial/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:175:23)
    at EthersProviderWrapper.send (/Users/kentarovadney/Desktop/Hardhat-tutorial/node_modules/@nomiclabs/hardhat-ethers/src/internal/ethers-provider-wrapper.ts:13:20)
    at Object.getSigners (/Users/kentarovadney/Desktop/Hardhat-tutorial/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:23:20)
    at getContractFactoryByAbiAndBytecode (/Users/kentarovadney/Desktop/Hardhat-tutorial/node_modules/@nomiclabs/hardhat-ethers/src/internal/helpers.ts:250:21)
    at main (/Users/kentarovadney/Desktop/Hardhat-tutorial/scripts/deploy.js:4:22)

    Caused by: FetchError: network timeout at: https://rpc.dusty.plasmnet.io:8545/
        at Timeout.<anonymous> (/Users/kentarovadney/Desktop/Hardhat-tutorial/node_modules/node-fetch/lib/index.js:1454:13)
        at listOnTimeout (node:internal/timers:557:17)
        at processTimers (node:internal/timers:500:7)
kentarovadney@Kentaros-MacBook-Air Hardhat-tutorial % 
```

**Comment by VadneyK** [comment]
tried it just now am having the same issue. However, connecting to a local node instead of the rpc worked.

I ran a local `plasm` node and connected to `http://localhost:9933` instead of `https://rpc.dusty.plasmnet.io:8545` and did `npx hardhat run --network dusty scripts/deploy.js`.

Ideally we should still figure out why the rpc was not connecting.

<img width="1214" alt="Screen Shot 2021-06-03 at 7 58 35 AM" src="https://user-images.githubusercontent.com/57117207/120666511-83516500-c441-11eb-80c1-d28fa3bae8aa.png">

**Comment by akru** [comment]
Public testnet rpc could be overloaded, I can suggest to use local node for tests

**Comment by VadneyK** [comment]
ok will do!
